name: Flutter Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        working-directory: myapp # <--- ESTO ES LO IMPORTANTE

      - name: Build APK
        run: flutter build apk --debug --split-per-abi
        working-directory: myapp # <--- Y ESTO TAMBIÉN

      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: myapp/build/app/outputs/flutter-apk/*.apk # <--- RUTA ACTUALIZADA
